export interface ChangelogEintrag {
  datum: string;
  titel: string;
}

/**
 * Neueste Änderung oben einfügen. Die Versionsnummer zählt automatisch
 * anhand der Listenlänge hoch – kein manuelles Nummerieren nötig.
 */
export const changelog: ChangelogEintrag[] = [
  { datum: "2026-07-31", titel: "Englische Oberfläche erweitert: Mitarbeiter-Ticketansicht komplett übersetzt (Ticketübersicht mit Filtern/Suche/Tabelle sowie Ticket-Detail mit Verlauf, Status/Zuweisung, SLA, Tags, Notizfeld)" },
  { datum: "2026-07-31", titel: "Englische Oberfläche erweitert: Startseite jetzt komplett übersetzt (auch der Mitarbeiter-/Admin-Bereich), außerdem Mein Profil und Dashboard" },
  { datum: "2026-07-31", titel: "Englische Oberfläche: DE/EN-Umschalter oben rechts (bzw. auf der Login-Seite). Sprache wird im Nutzerkonto gespeichert (geräteübergreifend). Bisher übersetzt: Login, Startseite, Kunden-Portal (neues Ticket, Ticket ansehen/antworten), Status-Badges – restliche Bereiche folgen schrittweise" },
  { datum: "2026-07-31", titel: "System-Mails (Statusänderung, Ticket geschlossen, neue Antwort, Mitarbeiter-Benachrichtigungen) sind jetzt pro Firma selbst anpassbar – neuer Bereich „E-Mail-Texte“ unter Verwaltung → Werkzeuge, mit Platzhaltern wie {{kunde_name}} oder {{ticket_nr}} und „Auf Standard zurücksetzen“" },
  { datum: "2026-07-31", titel: "Fix: Schnellzugriff-Ticketbuttons waren für super_admin komplett ausgeblendet (auch mit ausgewählter Firma) statt nur ohne Firmen-Kontext – jetzt sichtbar, sobald eine Firma aktiv ist; der zwischenzeitlich hinzugefügte „+ Neues Ticket“-Button auf dem Dashboard wurde auf Wunsch wieder entfernt" },
  { datum: "2026-07-31", titel: "Kunde bekommt jetzt automatisch eine Mail mit direktem Bewertungslink (👍/👎, ohne Login), sobald sein Ticket geschlossen wird – egal ob manuell oder automatisch durch die Inaktivitäts-Regel; vorher gab es dafür keine Benachrichtigung, die Bewertung war nur sichtbar, wenn der Kunde zufällig selbst ins Portal ging" },
  { datum: "2026-07-31", titel: "Startseite: „Neues Ticket“-Button im Schnellzugriff für Mitarbeiter ergänzt (bisher gab es dort nur „Alle Tickets“)" },
  { datum: "2026-07-31", titel: "Dashboard: „+ Neues Ticket“-Button ergänzt (oben neben „Zurück“), damit ein Ticket nicht erst über die Ticketübersicht angelegt werden muss" },
  { datum: "2026-07-31", titel: "Fix: Tabelle „kunden_preise“ (Individueller Minutenpreis) war nie tatsächlich angelegt worden, obwohl im Schema dokumentiert – dadurch scheiterte „Konten zusammenführen“ und das Preis-Feature war seit jeher unbenutzbar; Tabelle nachträglich angelegt" },
  { datum: "2026-07-31", titel: "Kundenverwaltung: weitere E-Mail-Adressen pro Kunde hinterlegbar (Mails von diesen Adressen landen automatisch beim richtigen Kunden statt einen neuen Account anzulegen) sowie neue Funktion „Konten zusammenführen“, um versehentlich doppelt angelegte Kunden-Accounts inkl. aller Tickets, Zeiteinträge, Dokumente, Preise, Todos, Dongles, Lizenzverträge und Hardware zu einem Konto zu vereinen" },
  { datum: "2026-07-31", titel: "Kundenverwaltung zeigt beim Aufklappen jetzt die Login-E-Mail-Adresse des Kunden an (nicht änderbar, nur zur Ansicht)" },
  { datum: "2026-07-31", titel: "Passwort vergessen (Link beim Login) und Passwort ändern (in Mein Profil, für alle Nutzer) – bisher gab es keine Möglichkeit, ein Passwort selbst zurückzusetzen" },
  { datum: "2026-07-31", titel: "Zwei Fixes am E-Mail-Import: eine fehlende Datenbank-Komponente (pg_net) ließ zeitweise alle Hintergrund-Jobs fehlschlagen (auch SLA-/Lizenz-Erinnerung, jetzt behoben); außerdem scheiterte der Import bisher an E-Mails von Absendern, die schon irgendeinen Account im System haben (z.B. ein Mitarbeiter beim Testen) – wird jetzt korrekt dem bestehenden Account zugeordnet statt übersprungen" },
  { datum: "2026-07-31", titel: "Mitarbeiter-Benachrichtigungsmail (Zuweisung/Statuswechsel/Kundenantwort) nennt jetzt den Namen der Person, die die Änderung ausgelöst hat" },
  { datum: "2026-07-31", titel: "E-Mail → Ticket funktioniert jetzt wirklich: eingehende Mails am Support-Postfach werden alle paar Minuten per IMAP abgerufen und automatisch zu Tickets (inkl. Anhängen); unbekannte Absender werden automatisch als Kunde angelegt, Antworten mit „#123“ im Betreff landen im bestehenden Ticket statt einem neuen" },
  { datum: "2026-07-31", titel: "Navigation Rail links bleibt jetzt fix am Bildschirmrand (inkl. Design-Umschalter/Profil-Symbol unten) statt mit langen Seiten mitzuscrollen" },
  { datum: "2026-07-30", titel: "Zugewiesener Techniker bekommt jetzt eine E-Mail, wenn ihm ein Ticket zugewiesen wird, jemand anderes den Status seines Tickets ändert oder der Kunde antwortet – nicht bei eigenen Aktionen" },
  { datum: "2026-07-30", titel: "E-Mail-Versand technisch stabilisiert: Supabase kann keine SMTP-Verbindungen direkt aufbauen (führte bislang dazu, dass gar keine Mails ankamen) – der Versand läuft jetzt über eine kleine Relay-Function auf Vercel, die echtes SMTP kann; für Firmen/Nutzer ändert sich nichts an der Eingabe" },
  { datum: "2026-07-30", titel: "Jede Firma kann jetzt unter Verwaltung → Integrationen eine eigene Absenderadresse (SMTP-Zugangsdaten) hinterlegen, statt sich ein gemeinsames Postfach mit allen anderen Firmen zu teilen; ohne eigene Angabe gilt weiterhin das zentrale Postfach als Fallback" },
  { datum: "2026-07-30", titel: "Ticket: Telefonnummer und E-Mail-Adresse des Kunden lassen sich jetzt per Klick auf das Kopieren-Symbol in die Zwischenablage kopieren" },
  { datum: "2026-07-30", titel: "E-Mail-Versand (Kundenbenachrichtigung, Plattform-Rechnung, SLA-/Lizenz-Erinnerung) von Resend auf einfaches SMTP über ein normales Postfach umgestellt – keine Domain-Verifizierung/DNS-Einrichtung mehr nötig" },
  { datum: "2026-07-30", titel: "Diktieren-Button zeigt in Firefox (und anderen nicht unterstützten Browsern) jetzt einen Hinweis statt einfach zu verschwinden – „geht mit Chrome, Edge oder Safari“" },
  { datum: "2026-07-30", titel: "Ticket: Telefonnummer und E-Mail des Kunden jetzt immer im Ticket-Kopf sichtbar (klickbar als Anruf-/Mail-Link); Antwortfeld unterstützt Spracheingabe (Diktieren-Button, Chrome/Edge)" },
  { datum: "2026-07-29", titel: "Neues Design (Phase 3 – Lizenz-Laufzeiten): „bis DD.MM.YYYY“-Text bei Dongles und Lizenzverträgen jetzt zusätzlich als Restlaufzeit-Balken sichtbar (grün/amber/rot je nach Dringlichkeit) statt reinem Text" },
  { datum: "2026-07-29", titel: "Neues Design (Phase 2 – Navigation & Dashboard): Firmenfarbe von DST Consulting auf Scan-Blau umgestellt; Navigation-Rail zeigt aktiven Bereich jetzt per Farbstreifen statt voller Füllfarbe; Dashboard-Kennzahlen und Diagramme in Mono-Ziffern mit farbigem Statusstreifen" },
  { datum: "2026-07-29", titel: "Neues Design (Phase 1 – Fundament): IBM Plex Sans/Mono statt Roboto, neuer „Scan-Blau“-Akzent statt Google-Blau, kühlere Neutraltöne, schärfere Eckenradien – wirkt auf die ganze App inkl. Login, da über die zentralen Design-Tokens gesteuert" },
  { datum: "2026-07-29", titel: "Neuer Verwaltungs-Tab „Dongles & Lizenzen“: Import, Nicht-zugeordnet-Pools und neue durchsuchbare Gesamtübersicht aller Dongles/Lizenzverträge (mit Kunde) sind jetzt aus der Kundenliste ausgelagert – die Kundenliste zeigt nur noch Kundendaten" },
  { datum: "2026-07-29", titel: "Fix: Anführungszeichen im Changelog-Text hatten den letzten Build unterbrochen (Vercel-Deploy fehlgeschlagen, alte Version blieb aktiv, kein Datenverlust)" },
  { datum: "2026-07-29", titel: "Kundenliste: zeigt standardmäßig nur noch die ersten 10 Kunden (mit „Alle anzeigen“), zusätzlich nach Hardware-Kategorie/-Wert filterbar (z.B. alle Kunden mit einem bestimmten Intraoral-Scanner)" },
  { datum: "2026-07-29", titel: "Fix: Kunden-Hardware zeigte firmenweite Vorschläge, die wie bereits zugeordnete (aber nicht löschbare) Geräte bei anderen Kunden wirkten – Vorschläge entfernt, nur noch tatsächlich zugeordnete Werte pro Kunde (löschbar) plus Freitext-Eingabe" },
  { datum: "2026-07-29", titel: "Kunden-Hardware erfassbar: frei konfigurierbare Kategorien (z.B. Intraoral-Scanner, Exocad-Datenbank, Fräsmaschine, Drucker), Werte per Klick aus Vorschlägen oder Freitext – in der Kundenliste und direkt im Ticket sichtbar/erfassbar" },
  { datum: "2026-07-29", titel: "Kunden-Todo-Liste jetzt auch bei der Ticketerstellung (kurze Übersicht offener Punkte) und direkt im Ticket (volle Liste mit Abhaken/Hinzufügen) sichtbar" },
  { datum: "2026-07-29", titel: "Lizenz-Ablauf-Erinnerung: Empfänger jetzt auf eine feste E-Mail-Adresse einstellbar (z.B. Support-Postfach) statt zwingend an alle Org-Admins – Kunden werden weiterhin nie kontaktiert" },
  { datum: "2026-07-29", titel: "Kundenliste: Nicht-zugeordnet-Pools (Dongles/Lizenzverträge) jetzt ebenfalls standardmäßig eingeklappt (5 Zeilen) statt komplett angezeigt; Dongle löschen fragt jetzt vorher nach Bestätigung" },
  { datum: "2026-07-29", titel: "Fix: Dongle-Löschung schlug fehl, wenn ein Ticket ihn referenzierte (fehlendes ON DELETE) – Ticket bleibt jetzt erhalten, verliert nur den Dongle-Link" },
  { datum: "2026-07-29", titel: "Dongle-Verwaltung: Liste pro Kunde jetzt suchbar und standardmäßig eingeklappt (3 Zeilen), Lizenzvertrag (Laufzeit/Ablauf) kann pro Dongle verknüpft und direkt in der Zeile eingesehen werden" },
  { datum: "2026-07-29", titel: "Kundenliste: Nicht zugeordnete Dongles/Lizenzverträge lassen sich jetzt nach Seriennummer filtern (praktisch bei großen Portal-Importen)" },
  { datum: "2026-07-29", titel: "Lizenzverträge: 2. exocad-Import (license_history) für Vertragslaufzeit/Ablaufdatum, „Bald fällige Lizenzverlängerungen“-Ansicht pro Kunde und organisationsweit, tägliche E-Mail-Erinnerung an Org-Admins (nur Hinweis, keine automatische Rechnung)" },
  { datum: "2026-07-29", titel: "Abrechnung: Ticket-Freiminuten pro Dongle werden jetzt automatisch abgezogen (Gesamtzeit ohne Abzug vs. berechnete Zeit, je Dongle eine Abzugszeile) – gilt in Rechnungsdetail und Monatsübersicht" },
  { datum: "2026-07-29", titel: "Kunden-Todoliste, Dongle-/Lizenzverwaltung (Wartungsvertrag, Freiminuten, Software-Module) mit Zuordnung bei Ticketerstellung sowie exocad-CSV-Import (anpassbares Spalten-Mapping, Nicht-zugeordnet-Pool)" },
  { datum: "2026-07-23", titel: "WhatsApp: optionales App-Secret-Feld – Server-Aufrufe schicken jetzt appsecret_proof mit, falls Meta „App-Secret-Proof erforderlich“ aktiviert hat" },
  { datum: "2026-07-23", titel: "Fix: WhatsApp-Webhook war nicht ausgerollt und prüfte den Verify-Token global statt pro Firma – jetzt mandantenfähig (Verify-Token und Access-Token je Firma aus der App)" },
  { datum: "2026-07-23", titel: "WhatsApp-Einrichtungsanleitung an Metas neue Konsole angepasst (Anwendungsfall → Schritt 2: Produktionseinrichtung statt der alten „API Setup“-Seite)" },
  { datum: "2026-07-23", titel: "Hilfe („?“ im Header) erklärt jetzt die App-Installation – mit Ein-Klick-Button, wo der Browser es unterstützt, sonst passender Anleitung für iPhone bzw. Browser-Menü" },
  { datum: "2026-07-23", titel: "Ticketsystem ist jetzt als App installierbar (PWA) – auf dem Handy/Desktop zum Homescreen hinzufügen, gleiche Datenbank wie im Browser" },
  { datum: "2026-07-22", titel: "Fix: Mitarbeiter, die nur per Mehrfach-Mitgliedschaft (nicht als Home-Firma) verknüpft sind, fehlten in Ticket-Zuweisung, Dashboard, Über uns, Kollegenliste und Mitarbeiterzahl der Plattform-Abrechnung" },
  { datum: "2026-07-22", titel: "Hero-Bild auf der Ticketseite wird größer dargestellt (passt sich am Bild-Seitenverhältnis an statt fester, knapper Höhe)" },
  { datum: "2026-07-22", titel: "Ticketübersicht: eigenen Standard-Status-Filter speicherbar (z.B. „In Bearbeitung“ statt immer „Offene“)" },
  { datum: "2026-07-22", titel: "Neues Ticket anlegen: Kunde-Feld jetzt durchsuchbar, mit „+ Neuer Kunde“ direkt aus dem Formular anlegbar" },
  { datum: "2026-07-22", titel: "Neues HowTo: Anwendungs-Anleitung erscheint einmalig beim ersten Login, danach jederzeit über das „?“-Icon im Header (rollenabhängig für Team bzw. Kunden)" },
  { datum: "2026-07-21", titel: "Neue Firma bekommt beim Anlegen automatisch eine eigene Landingpage (Slug wird aus dem Namen abgeleitet, URL direkt sichtbar)" },
  { datum: "2026-07-21", titel: "Kunden-Zugangsseite (?neukunde=...): gut sichtbarer FAQ-Button, wenn die Firma öffentliche FAQ-Einträge hat" },
  { datum: "2026-07-21", titel: "WhatsApp-Anleitung auf permanenten System-User-Token umgestellt, neuer 'Verbindung testen'-Button prüft Meta-Zugang direkt" },
  { datum: "2026-07-21", titel: "Volltextsuche: echte Postgres-Volltextsuche (wortweise, reihenfolge-unabhängig) statt einfacher Zeichenketten-Suche, jetzt auch im Kundenportal" },
  { datum: "2026-07-21", titel: "SLA-Eskalation: Reaktions-/Lösungsfristen werden jetzt tatsächlich gesetzt, bei Verstoß automatische Mail + Badge/Filter 'SLA verletzt'" },
  { datum: "2026-07-21", titel: "Fix: nächtlicher Auto-Schließen-Cronjob lief wegen falschem Auth-Token vermutlich seit Einführung nie durch" },
  { datum: "2026-07-21", titel: "Fix: Navigation Rail – Dashboard/Postfach/Plattform-Abrechnung/Verwaltung/Firmeninfo/Profil überschrieben sich teils gegenseitig (fehlende Zustands-Resets)" },
  { datum: "2026-07-18", titel: "Titel & Spruch der Anmeldeseite jetzt vom Super-Admin änderbar (Plattform-Abrechnung → Anmeldeseite)" },
  { datum: "2026-07-18", titel: "Neues Design: Google Material 3 – Navigation Rail, Roboto-Schrift, neue Formsprache und Farben (hell & dunkel)" },
  { datum: "2026-07-06", titel: "KI-Assistent nutzt jetzt claude-sonnet-5 statt des veralteten claude-sonnet-4-6" },
  { datum: "2026-07-03", titel: "Dateien per Drag & Drop ins Kommentarfeld ziehen (Techniker- und Kunden-Antworten)" },
  { datum: "2026-07-03", titel: "Fix: Zugangslinks vorlade-sicher – WhatsApp & Co. können Einmal-Links nicht mehr vorzeitig verbrauchen" },
  { datum: "2026-07-03", titel: "Mehrfach-Mitgliedschaft: Mitarbeiter können bei mehreren Firmen gleichzeitig aktiv sein, Firmen-Umschalter im Header" },
  { datum: "2026-07-03", titel: "Fix: Nutzer-Zuweisung entfernte Person unbemerkt aus anderer Firma – jetzt mit Warnung" },
  { datum: "2026-07-03", titel: "Plattform-Rechnungen: Zahlungsziel, rechtlicher Hinweis, Freitext, Steuernummer" },
  { datum: "2026-07-03", titel: "Header-Icons größer und mit Gruppen-Trennern (bessere Klick-Trefferquote)" },
  { datum: "2026-07-03", titel: "Plattform-Abrechnung: Tarife mit Mitarbeiter-Staffeln, Rechnungen an Firmen per E-Mail" },
  { datum: "2026-07-03", titel: "Dashboard-Charts: Neon-Hover statt grauem Kasten, sanftes Aufbau-Animation" },
  { datum: "2026-07-03", titel: "Kunden-Filter in Ticketübersicht mit Suchfeld durchsuchbar" },
  { datum: "2026-07-03", titel: "Fix: Produkte speichern als Super-Admin blockiert (RLS-Policy korrigiert)" },
  { datum: "2026-07-03", titel: "Fix: Produkte ließen sich nicht speichern (fehlende Datenbanktabelle nachgezogen)" },
  { datum: "2026-07-03", titel: "Änderungsverlauf: anklickbare Versionsnummer im Header" },
  { datum: "2026-07-03", titel: "Einheit \"Minute\" bei Produkten ergänzt" },
  { datum: "2026-07-03", titel: "Makro-Bug behoben, Produktdatenbank + Rechnungspositionen" },
  { datum: "2026-07-03", titel: "UI grafischer: Prioritäts-Farbstreifen, Icon-Boxen, KPI-Icons" },
  { datum: "2026-07-02", titel: "Buzzer-Sounds: 4 Presets + eigene Sounds hochladbar" },
  { datum: "2026-07-02", titel: "Zeiteinträge im Ticketverlauf sichtbar" },
  { datum: "2026-07-02", titel: "Desktop-Layout: breiter Container, Zweispalten-Ticketdetail" },
  { datum: "2026-07-02", titel: "Fix: kein App-Reload bei Tab-Wechsel, Warnung bei ungespeicherten Daten" },
  { datum: "2026-07-02", titel: "Startseiten-Zahlen klickbar: Mir zugewiesen, Wartet, Offene mit Filter" },
  { datum: "2026-07-02", titel: "Team: E-Mail sichtbar und änderbar" },
  { datum: "2026-07-02", titel: "Anleitungen bei allen Werkzeugen" },
  { datum: "2026-07-02", titel: "KI-Assistent, Recharts-Dashboard, Skeleton-Loading, Leer-Zustände" },
  { datum: "2026-07-02", titel: "Volltextsuche aktiviert, Hero-Bild resized statt abschneidet" },
  { datum: "2026-07-02", titel: "Öffentliche FAQ-Seite als eigene URL (?faq=slug)" },
  { datum: "2026-07-02", titel: "Konfigurations-Anleitungen direkt bei jeder Integration" },
  { datum: "2026-07-02", titel: "Public API + Webhooks: API-Keys, Endpunkte, Doku direkt in der App" },
  { datum: "2026-07-01", titel: "FAQ, Ticket-Merge, MeinProfil Kunden, Reporting-Export" },
  { datum: "2026-07-01", titel: "Supermann-Button: Super-Admin Schnellrückkehr zur Gesamtübersicht" },
  { datum: "2026-07-01", titel: "SuperAdmin Dashboard: Firmen-Zeilen klickbar, direkt in Firma wechseln" },
  { datum: "2026-07-01", titel: "Verwaltung mit Tabs (Firma/Team/Kunden/Werkzeuge), Startseite-Buttons direkt verknüpft" },
  { datum: "2026-07-01", titel: "Super-Admin Startseite: Tickets ausgeblendet, Schnell-Nutzer-Anlegen" },
  { datum: "2026-07-01", titel: "Zwei separate Dashboards: Super-Admin (alle Firmen) und Firma-Dashboard" },
  { datum: "2026-07-01", titel: "Fancy Buzzer: Ripple-Animation, Sound, 3D-Optik" },
  { datum: "2026-07-01", titel: "Willkommens-Startseite mit Schnellzugriff und Live-Zahlen" },
  { datum: "2026-07-01", titel: "Reporting-Dashboard: KPIs, Volumen-Chart, Team-Auslastung, CSAT" },
  { datum: "2026-07-01", titel: "Edge Function: auto-schließen" },
  { datum: "2026-07-01", titel: "Ticket-Vorlagen: anlegen in Verwaltung, auswählbar beim neuen Ticket" },
  { datum: "2026-07-01", titel: "Zendesk-Features: Makros, Tags, SLA, CSAT, Kollisionswarnung, Volltextsuche" },
  { datum: "2026-06-30", titel: "Ticketverlauf: neueste Nachricht zuerst" },
  { datum: "2026-06-30", titel: "Farbcodierte Status-Badges mit Puls-Animation" },
  { datum: "2026-06-30", titel: "Fehler beim Anhang-Upload sichtbar machen statt stillschweigend verschlucken" },
  { datum: "2026-06-30", titel: "Einstellbare Logo-Größe auf der Rechnung" },
  { datum: "2026-06-30", titel: "Fehler beim Laden von Team/Kunden nicht mehr stillschweigend verschlucken" },
  { datum: "2026-06-30", titel: "Fix: Anhänge wurden nach Upload nicht angezeigt (Race Condition)" },
  { datum: "2026-06-30", titel: "Datenschutzerklärung pro Firma: Link oder eigener Text, Pflicht-Checkbox" },
  { datum: "2026-06-30", titel: "Direkter Link zur Ticketübersicht von überall im Header" },
  { datum: "2026-06-30", titel: "USt-IdNr. und steuerfreie innergemeinschaftliche Lieferung, Lieferdatum-Hinweis" },
  { datum: "2026-06-30", titel: "Registrierungsseite breiter, Browser-Autofill-Farbe gefixt" },
  { datum: "2026-06-30", titel: "Hübschere Datei-Auswahl, Zeitstempel im Nachrichtenverlauf" },
  { datum: "2026-06-30", titel: "Datei-Anhänge beim Antworten im Ticket-Verlauf (Team und Kunde)" },
  { datum: "2026-06-30", titel: "Vorname/Nachname getrennt, Logo-Resize-Fix" },
  { datum: "2026-06-30", titel: "Erklärtext, Kontaktbox und lockerer Spruch auf Registrierungsseite" },
  { datum: "2026-06-30", titel: "Logos skalieren statt zuschneiden" },
  { datum: "2026-06-30", titel: "Bildvalidierung beim Logo-/Hero-Upload (Größe, Mindestmaße)" },
  { datum: "2026-06-30", titel: "Logo deutlich vergrößert, Formularreihenfolge angepasst" },
  { datum: "2026-06-30", titel: "Logo/Hero-Bild größer, Telefon/Adresse bei Selbstregistrierung" },
  { datum: "2026-06-30", titel: "Fix: Preisvalidierung blockierte Slug-Speichern, RPC statt View für Registrierungslink" },
  { datum: "2026-06-30", titel: "Öffentlicher Selbstregistrierungslink pro Firma" },
  { datum: "2026-06-30", titel: "Fix: Ticketübersicht filterte nicht explizit nach Organisation" },
  { datum: "2026-06-30", titel: "Fix: Ticket-Auswahl beim Firmenwechsel als Super-Admin zurücksetzen" },
  { datum: "2026-06-30", titel: "Super-Admin: aktiver Firmenkontext für Tickets/Abrechnung/Postfach" },
  { datum: "2026-06-30", titel: "Bestehenden Nutzer einer Firma zuweisen, klare Fehlermeldung bei Doppel-Account" },
  { datum: "2026-06-30", titel: "Internes Postfach: Org-Admin an Super-Admin" },
  { datum: "2026-06-30", titel: "Branding pro Firma: Motto, Akzentfarbe, Hero-Bild" },
  { datum: "2026-06-30", titel: "Super-Admin-Übersicht über alle Firmen" },
  { datum: "2026-06-29", titel: "Land und MwSt-Satz pro Kunde, Monatsübersicht mit Netto/MwSt/Brutto" },
  { datum: "2026-06-29", titel: "Adresse in Straße/Hausnummer/PLZ/Ort aufteilen, Kundensuche" },
  { datum: "2026-06-29", titel: "Online-Status für Team und Kunden via Realtime Presence" },
  { datum: "2026-06-29", titel: "Preis-Historie mit Gültigkeitsdatum pro Kunde" },
  { datum: "2026-06-29", titel: "Warnungen vor Link-Versand per WhatsApp ergänzt" },
  { datum: "2026-06-29", titel: "Firmenname und -adresse in Zugangsdaten-Nachricht durchreichen" },
  { datum: "2026-06-29", titel: "Neue Zugangslinks anfordern, Gültigkeitsdauer in Nachricht" },
  { datum: "2026-06-29", titel: "Rechnungsdetail mit Einzelposten, Rabatten und Druckansicht" },
  { datum: "2026-06-29", titel: "Einladungslink-Erkennung robuster machen, Passwort-Setzen erzwingen" },
  { datum: "2026-06-29", titel: "Ausführlichere Zugangsnachricht mit Firmenname und Login-URL" },
  { datum: "2026-06-29", titel: "Preisfelder auf Euro umgestellt (Cent-Bug gefixt), Standardpreis editierbar" },
  { datum: "2026-06-29", titel: "Einladungslink über WhatsApp/Mail/Kopieren teilen statt Supabase-Mail" },
  { datum: "2026-06-29", titel: "Optionales Passwort statt Mail-Einladung" },
  { datum: "2026-06-29", titel: "Kunden/Mitarbeiter deaktivieren statt löschen" },
  { datum: "2026-06-29", titel: "Kunde kann eigenes Ticket schließen, Status sichtbar im Portal" },
  { datum: "2026-06-29", titel: "Offene Tickets als Standard, Ungelesen-Markierung für Kundennachrichten" },
  { datum: "2026-06-29", titel: "Firmenkontakt + Team-Übersicht für Kunden" },
  { datum: "2026-06-29", titel: "Mitarbeiterverwaltung, Zuweisung bei Ticket-Anlage" },
  { datum: "2026-06-29", titel: "Zendesk-artige Übersicht: Suche, Kundenfilter, Ticket-Nummern" },
  { datum: "2026-06-29", titel: "Manuelles Anlegen von Kunden und Tickets" },
  { datum: "2026-06-29", titel: "Kundenverwaltung: Adresse, Notizen, individueller Preis" },
  { datum: "2026-06-29", titel: "Dateinamen vor Upload säubern (Storage Invalid-Key-Fix)" },
  { datum: "2026-06-29", titel: "RLS-Schreibrechte komplettiert, Team-Verwaltung" },
  { datum: "2026-06-28", titel: "Ticketübersicht neu gestaltet, JetBrains Mono für Badges" },
  { datum: "2026-06-28", titel: "Verwaltungsbereich: Firmenprofil, Einladungen, Organisationen" },
  { datum: "2026-06-28", titel: "Login-Design, Storage-Fix, Avatare, Dark Mode" },
  { datum: "2026-06-28", titel: "Projekt-Start: Grundgerüst mit Tickets, Auth und Supabase-Anbindung" },
];

export const aktuelleVersion = changelog.length;
